language: go

go:
  - 1.2

before_install:
  - go get github.com/jteeuwen/go-bindata/...
  - export PATH=$PATH:/home/travis/gopath/bin
  - go-bindata

install: 
  - go get -v ./...

services:
  - cassandra